/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.airlinereservation;

/**
 *
 * @author amit
 */
public class contactus extends javax.swing.JInternalFrame {

    /**
     * Creates new form contactus
     */
    public contactus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();

        jTextArea1.setBackground(new java.awt.Color(255, 153, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Customer Support:\nOur customer support representatives are available 24/7 to assist you with any issues or questions you may have regarding your flight bookings or any other inquiries.\n\nEmail: support@sagarairlinereservation.com\nPhone: [+1 (XXX) XXX-XXXX] (For international customers, please use the appropriate country code)\n\nBooking Assistance:\nIf you need help with making a reservation or have questions related to your existing booking, our booking assistance team is here to help.\n\nEmail: bookings@sagarairlinereservation.com\nPhone: [+1 (XXX) XXX-XXXX] (For international customers, please use the appropriate country code)\n\n\nFrequent Flyer Program:\nFor inquiries related to our frequent flyer rewards program, points redemption, or account management, please reach out to our frequent flyer support team.\n\nEmail: frequentflyer@sagarairlinereservation.com\nPhone: [+1 (XXX) XXX-XXXX] (For international customers, please use the appropriate country code)\n\nCorporate and Business Solutions:\nIf you represent a corporate entity or require business travel solutions, our specialized team is ready to cater to your needs.\n\nEmail: corporate@sagarairlinereservation.com\nPhone: [+1 (XXX) XXX-XXXX] (For international customers, please use the appropriate country code)\nMedia and Press Inquiries:\nFor media inquiries, press releases, or partnership opportunities, please contact our media relations team.\n\nEmail: media@sagarairlinereservation.com\nPhone: [+1 (XXX) XXX-XXXX] (For international customers, please use the appropriate country code)\n\nAddress:\nSagar Airline Reservation System\n1234 Skyway Avenue\nCity, State/Province, Postal Code\nCountry\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        setBackground(new java.awt.Color(255, 153, 102));

        jTextArea2.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("                                                                                  Customer Support:\nOur customer support representatives are available 24/7 to assist you with any issues or questions you may have regarding your flight bookings or any other inquiries.\nEmail: support@sagarairlinereservation.comm");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setBackground(new java.awt.Color(204, 255, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("                                                                                      Booking Assistance:\nIf you need help with making a reservation or have questions related to your existing booking, our booking assistance team is here to help.\nEmail: bookings@sagarairlinereservation.com\n");
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("                                                                               \n                                                                               Frequent Flyer Program:\nFor inquiries related to our frequent flyer rewards program, points redemption, or account management, please reach out to our frequent flyer support team.\nEmail: frequentflyer@sagarairlinereservation.com\n");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("                                                                               Corporate and Business Solutions:\nIf you represent a corporate entity or require business travel solutions, our specialized team is ready to cater to your needs.\nEmail: corporate@sagarairlinereservation.com\n");
        jScrollPane5.setViewportView(jTextArea5);

        jTextArea6.setBackground(new java.awt.Color(0, 204, 153));
        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("                                                                                       Media and Press Inquiries:\nFor media inquiries, press releases, or partnership opportunities, please contact our media relations team.\nEmail: media@sagarairlinereservation.com\nPhone: [8896754392] ");
        jScrollPane6.setViewportView(jTextArea6);

        jTextArea7.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("Address:\nSagar Airline Reservation System\n1234 jhansi Road\nJHANSI UP\nINDIA");
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane6))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    // End of variables declaration//GEN-END:variables
}
